[package]
name = "incarnate"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "3.2.23", features = ["derive"] }
include_dir = "0.7.3"
struct-field-names-as-array = "0.1.4"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["tracing-log"] }
