[package]
name = "incarnate"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
clap-interactive = "0.2.1"
include_dir = "0.7.3"
struct-field-names-as-array = "0.1.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
